package com.cmhk.business.module.admin.controller;
import com.cmhk.business.common.ApiResponse;import com.cmhk.business.config.AdminAuthInterceptor;import com.cmhk.business.module.admin.entity.*;import com.cmhk.business.module.admin.service.SecondarySettlementService;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.util.List;
@RestController @RequestMapping("/api/admin/secondary")
public class AdminSecondaryController {private final SecondarySettlementService service;public AdminSecondaryController(SecondarySettlementService service){this.service=service;}
 @GetMapping("/channels")public ApiResponse<List<SecondaryChannel>> channels(){return ApiResponse.success(service.channels());}@PostMapping("/channels")public ApiResponse<SecondaryChannel> createChannel(@RequestBody SecondaryChannel v,@RequestAttribute(AdminAuthInterceptor.ADMIN_USERNAME)String op){return ApiResponse.success(service.saveChannel(null,v,op));}@PutMapping("/channels/{id}")public ApiResponse<SecondaryChannel> updateChannel(@PathVariable Long id,@RequestBody SecondaryChannel v,@RequestAttribute(AdminAuthInterceptor.ADMIN_USERNAME)String op){return ApiResponse.success(service.saveChannel(id,v,op));}
 @GetMapping("/rules")public ApiResponse<List<SecondaryCommissionRule>> rules(){return ApiResponse.success(service.rules());}@PostMapping("/rules")public ApiResponse<SecondaryCommissionRule> createRule(@RequestBody SecondaryCommissionRule v,@RequestAttribute(AdminAuthInterceptor.ADMIN_USERNAME)String op){return ApiResponse.success(service.saveRule(null,v,op));}@PutMapping("/rules/{id}")public ApiResponse<SecondaryCommissionRule> updateRule(@PathVariable Long id,@RequestBody SecondaryCommissionRule v,@RequestAttribute(AdminAuthInterceptor.ADMIN_USERNAME)String op){return ApiResponse.success(service.saveRule(id,v,op));}
 @GetMapping("/records")public ApiResponse<List<SecondaryCommissionRecord>> records(){return ApiResponse.success(service.records());}@PostMapping("/records/calculate")public ApiResponse<SecondaryCommissionRecord> calculate(@RequestBody SecondarySettlementService.CalculateRequest r,@RequestAttribute(AdminAuthInterceptor.ADMIN_USERNAME)String op){return ApiResponse.success(service.calculate(r,op));}
 @PostMapping("/records/{id}/adjust")public ApiResponse<SecondaryCommissionRecord> adjust(@PathVariable Long id,@RequestBody AdjustRequest r,@RequestAttribute(AdminAuthInterceptor.ADMIN_USERNAME)String op){return ApiResponse.success(service.adjust(id,r.amount(),r.reason(),op));}@PostMapping("/records/{id}/confirm")public ApiResponse<SecondaryCommissionRecord> confirm(@PathVariable Long id,@RequestAttribute(AdminAuthInterceptor.ADMIN_USERNAME)String op){return ApiResponse.success(service.confirm(id,op));}public record AdjustRequest(BigDecimal amount,String reason){}
}
