<script setup lang="ts">
import {computed} from 'vue';import {useRoute,useRouter} from 'vue-router';import {clearSession,session} from '../api/http';
import {HomeFilled,CreditCard,User,Document,Connection,OfficeBuilding,DataAnalysis,List,UploadFilled,WarningFilled,Tickets,Setting,SwitchButton,Bell,UserFilled,Goods} from '@element-plus/icons-vue'
const route=useRoute(),router=useRouter();const active=computed(()=>route.path);const current=session();const account=computed(()=>current?.username||'管理员');const isAdmin=computed(()=>current?.role==='ADMIN');const isChannelScope=computed(()=>current?.scopeType==='CHANNEL');
function logout(){clearSession();router.replace('/login')}
</script>
<template><div class="admin-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark"><span>JOIN</span><span>COM</span></div><div><b>聚客联盟</b><small>CMHK 管理后台</small></div></div><el-scrollbar class="menu-scroll"><el-menu :default-active="active" router unique-opened background-color="#342626" text-color="#fff" active-text-color="#fff">
 <el-menu-item v-if="!isChannelScope" index="/"><el-icon><HomeFilled/></el-icon><span>首页</span></el-menu-item><el-sub-menu v-if="!isChannelScope" index="resources"><template #title><el-icon><CreditCard/></el-icon><span>资源管理</span></template><el-menu-item index="/resources/iccids">ICCID 卡池</el-menu-item><el-menu-item index="/resources/virtual-iccid-replacement">虚拟卡替换</el-menu-item><el-menu-item index="/resources/referral-numbers">推荐号码接龙</el-menu-item></el-sub-menu><el-menu-item index="/customers"><el-icon><User/></el-icon><span>客户管理</span></el-menu-item><el-menu-item index="/orders"><el-icon><Document/></el-icon><span>订单管理</span></el-menu-item><el-menu-item v-if="!isChannelScope" index="/products"><el-icon><Goods/></el-icon><span>产品管理</span></el-menu-item>
 <el-menu-item v-if="!isChannelScope" index="/tasks"><el-icon><Tickets/></el-icon><span>任务中心</span></el-menu-item>
 <el-sub-menu v-if="!isChannelScope" index="reconciliation"><template #title><el-icon><DataAnalysis/></el-icon><span>对账管理</span></template><el-menu-item index="/reconciliation/import"><el-icon><UploadFilled/></el-icon>甲方文件导入</el-menu-item><el-menu-item index="/reconciliation/records"><el-icon><Tickets/></el-icon>对账记录</el-menu-item><el-menu-item index="/reconciliation/exceptions"><el-icon><WarningFilled/></el-icon>异常匹配</el-menu-item></el-sub-menu>
 <el-sub-menu index="secondary"><template #title><el-icon><Connection/></el-icon><span>渠道管理</span></template><el-menu-item index="/secondary/channels"><el-icon><OfficeBuilding/></el-icon>渠道档案</el-menu-item><el-menu-item v-if="!isChannelScope" index="/secondary/rules"><el-icon><Setting/></el-icon>结算规则</el-menu-item><el-menu-item index="/secondary/orders"><el-icon><Document/></el-icon>渠道订单</el-menu-item><el-menu-item index="/secondary/settlements"><el-icon><DataAnalysis/></el-icon>结算记录</el-menu-item></el-sub-menu>
 <el-menu-item v-if="isAdmin" index="/users"><el-icon><Setting/></el-icon><span>管理员</span></el-menu-item><el-menu-item v-if="!isChannelScope" index="/logs"><el-icon><List/></el-icon><span>操作日志</span></el-menu-item></el-menu></el-scrollbar></aside>
 <main class="workspace"><header class="topbar"><div><h2>你好，{{account}}</h2><p>欢迎回来，今天也请稳妥处理每一笔业务。</p></div><div class="top-actions"><button aria-label="当前账号"><el-icon><UserFilled/></el-icon></button><button aria-label="通知"><el-icon><Bell/></el-icon></button><button aria-label="退出登录" @click="logout"><el-icon><SwitchButton/></el-icon></button></div></header><section class="content"><router-view/></section></main></div></template>
<style scoped>
.admin-shell{height:100%;display:flex}.sidebar{width:220px;min-width:220px;height:100%;background:#342626;color:#fff;display:flex;flex-direction:column}.brand{height:80px;display:flex;align-items:center;padding:0 22px;gap:14px;border-bottom:1px solid #c81f1f}.brand-mark{width:43px;height:43px;background:#fff;border-radius:5px;color:#252020;display:flex;flex-direction:column;align-items:center;justify-content:center;font:bold 12px/12px Arial;position:relative}.brand-mark:after{content:"";position:absolute;left:7px;right:7px;top:21px;height:2px;background:#c81f1f}.brand b{font-size:19px;letter-spacing:1px;display:block}.brand small{display:block;margin-top:3px;color:#cfc6c6;font-size:10px}.menu-scroll{flex:1}.el-menu{border-right:0;padding:22px 0}.el-menu-item,.el-sub-menu :deep(.el-sub-menu__title){height:52px;margin:4px 14px 4px 0;padding-left:32px!important;border-radius:0 8px 8px 0;font-size:15px}.el-menu-item.is-active{background:#c81f1f!important}.el-sub-menu :deep(.el-menu-item){min-width:0;margin-left:0;padding-left:48px!important}.workspace{flex:1;min-width:0;height:100%;overflow:auto}.topbar{height:80px;padding:14px 28px 0 32px;display:flex;align-items:flex-start;justify-content:space-between;background:#f7f8fb}.topbar h2{margin:0;font-size:21px}.topbar p{margin:6px 0 0;color:#aaa;font-size:13px}.top-actions{display:flex;align-items:center;gap:17px;padding-top:9px}.top-actions button{border:0;background:transparent;width:30px;height:30px;padding:0;color:#565656;cursor:pointer}.top-actions .el-icon{font-size:24px}.content{padding:24px 32px 34px;min-height:calc(100% - 80px)}@media (max-width:1440px){.topbar{padding-left:24px;padding-right:22px}.content{padding:20px 22px 28px}}
</style>
