import http from './http'
export const api={
 login:(data:any)=>http.post('/auth/login',data),dashboard:()=>http.get('/dashboard'),logs:(params?:any)=>http.get('/logs',{params}),
 users:()=>http.get('/users'),createUser:(d:any)=>http.post('/users',d),updateUser:(id:number,d:any)=>http.put(`/users/${id}`,d),changeUserPassword:(id:number,password:string)=>http.post(`/users/${id}/password`,{password}),changeUserStatus:(id:number,status:string)=>http.post(`/users/${id}/status`,{status}),
 customers:(params?:any)=>http.get('/customers',{params}),customerChannels:()=>http.get('/customers/channels'),customer:(id:number)=>http.get(`/customers/${id}`),createCustomer:(d:any)=>http.post('/customers',d),updateCustomer:(id:number,d:any)=>http.put(`/customers/${id}`,d),
 orders:(params?:any)=>http.get('/orders',{params}),order:(id:number)=>http.get(`/orders/${id}`),createOrder:(d:any)=>http.post('/orders',d),updateOrder:(id:number,d:any)=>http.put(`/orders/${id}`,d),
 iccids:(params?:any)=>http.get('/iccids',{params}),createIccid:(d:any)=>http.post('/iccids',d),importIccids:(d:FormData)=>http.post('/iccids/import',d),assignIccid:(id:number,d:any)=>http.post(`/iccids/${id}/assign`,d),unassignIccid:(id:number,d:any)=>http.post(`/iccids/${id}/unassign`,d),useIccid:(id:number)=>http.post(`/iccids/${id}/used`),disableIccid:(id:number,d:any)=>http.post(`/iccids/${id}/disable`,d),iccidHistory:(id:number)=>http.get(`/iccids/${id}/history`),
 reconciliationPreview:(d:FormData)=>http.post('/reconciliation/preview',d),reconciliationConfirm:(id:number)=>http.post(`/reconciliation/${id}/confirm`),imports:()=>http.get('/reconciliation/imports'),importDetail:(id:number)=>http.get(`/reconciliation/imports/${id}`),exceptions:()=>http.get('/reconciliation/exceptions'),manualMatch:(id:number,orderId:number)=>http.post(`/reconciliation/rows/${id}/match`,{orderId}),
 channels:()=>http.get('/secondary/channels'),createChannel:(d:any)=>http.post('/secondary/channels',d),updateChannel:(id:number,d:any)=>http.put(`/secondary/channels/${id}`,d),rules:()=>http.get('/secondary/rules'),createRule:(d:any)=>http.post('/secondary/rules',d),updateRule:(id:number,d:any)=>http.put(`/secondary/rules/${id}`,d),records:()=>http.get('/secondary/records'),calculate:(d:any)=>http.post('/secondary/records/calculate',d),adjust:(id:number,d:any)=>http.post(`/secondary/records/${id}/adjust`,d),confirmSettlement:(id:number)=>http.post(`/secondary/records/${id}/confirm`)
}
