import http from './http'
export const api={
 login:(data:any)=>http.post('/auth/login',data),dashboard:()=>http.get('/dashboard'),logs:(params?:any)=>http.get('/logs',{params}),
 users:()=>http.get('/users'),createUser:(d:any)=>http.post('/users',d),updateUser:(id:number,d:any)=>http.put(`/users/${id}`,d),changeUserPassword:(id:number,password:string)=>http.post(`/users/${id}/password`,{password}),changeUserStatus:(id:number,status:string)=>http.post(`/users/${id}/status`,{status}),
 customers:(params?:any)=>http.get('/customers',{params}),customerChannels:()=>http.get('/customers/channels'),customerOwners:()=>http.get('/customers/owners'),customer:(id:number)=>http.get(`/customers/${id}`),createCustomer:(d:any)=>http.post('/customers',d),updateCustomer:(id:number,d:any)=>http.put(`/customers/${id}`,d),customerFollowUps:(id:number)=>http.get(`/customers/${id}/follow-ups`),addCustomerFollowUp:(id:number,d:any)=>http.post(`/customers/${id}/follow-ups`,d),
 orders:(params?:any)=>http.get('/orders',{params}),order:(id:number)=>http.get(`/orders/${id}`),orderStatusHistory:(id:number)=>http.get(`/orders/${id}/status-history`),createOrder:(d:any)=>http.post('/orders',d),updateOrder:(id:number,d:any)=>http.put(`/orders/${id}`,d),
 iccids:(params?:any)=>http.get('/iccids',{params}),createIccid:(d:any)=>http.post('/iccids',d),importIccids:(d:FormData)=>http.post('/iccids/import',d),assignIccid:(id:number,d:any)=>http.post(`/iccids/${id}/assign`,d),unassignIccid:(id:number,d:any)=>http.post(`/iccids/${id}/unassign`,d),useIccid:(id:number)=>http.post(`/iccids/${id}/used`),disableIccid:(id:number,d:any)=>http.post(`/iccids/${id}/disable`,d),replaceVirtualIccid:(id:number,d:any)=>http.post(`/iccids/${id}/replace`,d),iccidHistory:(id:number)=>http.get(`/iccids/${id}/history`),
 referralChains:()=>http.get('/referral-numbers/chains'),createReferralChain:(d:any)=>http.post('/referral-numbers/chains',d),changeReferralChainStatus:(id:number,d:any)=>http.post(`/referral-numbers/chains/${id}/status`,d),referralNumbers:(params?:any)=>http.get('/referral-numbers',{params}),eligibleReferralOrders:()=>http.get('/referral-numbers/eligible-orders'),addReferralCandidate:(chainId:number,d:any)=>http.post(`/referral-numbers/chains/${chainId}/candidates`,d),previewReferralImport:(chainId:number,d:FormData)=>http.post(`/referral-numbers/chains/${chainId}/import/preview`,d),confirmReferralImport:(chainId:number,d:FormData)=>http.post(`/referral-numbers/chains/${chainId}/import/confirm`,d),designateReferralHead:(chainId:number,d:any)=>http.post(`/referral-numbers/chains/${chainId}/head`,d),reserveReferral:(chainId:number,d:any)=>http.post(`/referral-numbers/chains/${chainId}/reserve`,d),releaseReferral:(id:number,d:any)=>http.post(`/referral-numbers/${id}/release`,d),completeReferral:(id:number,d:any)=>http.post(`/referral-numbers/${id}/complete-onboarding`,d),disableReferral:(id:number,d:any)=>http.post(`/referral-numbers/${id}/disable`,d),referralHistory:(id:number)=>http.get(`/referral-numbers/${id}/history`),resourceDiagnostics:()=>http.get('/resources/diagnostics'),orderResources:(id:number)=>http.get(`/resources/orders/${id}`),
 reconciliationPreview:(d:FormData)=>http.post('/reconciliation/preview',d),reconciliationConfirm:(id:number)=>http.post(`/reconciliation/${id}/confirm`),imports:()=>http.get('/reconciliation/imports'),importDetail:(id:number)=>http.get(`/reconciliation/imports/${id}`),exceptions:()=>http.get('/reconciliation/exceptions'),manualMatch:(id:number,orderId:number)=>http.post(`/reconciliation/rows/${id}/match`,{orderId}),
 channels:()=>http.get('/channels'),createChannel:(d:any)=>http.post('/channels',d),updateChannel:(id:number,d:any)=>http.put(`/channels/${id}`,d),rules:()=>http.get('/secondary/rules'),createRule:(d:any)=>http.post('/secondary/rules',d),updateRule:(id:number,d:any)=>http.put(`/secondary/rules/${id}`,d),records:()=>http.get('/secondary/records'),calculate:(d:any)=>http.post('/secondary/records/calculate',d),adjust:(id:number,d:any)=>http.post(`/secondary/records/${id}/adjust`,d),confirmSettlement:(id:number)=>http.post(`/secondary/records/${id}/confirm`),
 plans:()=>http.get('/products/plans'),createPlan:(d:any)=>http.post('/products/plans',d),updatePlan:(id:number,d:any)=>http.put(`/products/plans/${id}`,d),disablePlan:(id:number)=>http.delete(`/products/plans/${id}`),offers:(planCode:string)=>http.get('/products/offers',{params:{planCode}}),createOffer:(d:any)=>http.post('/products/offers',d),updateOffer:(id:number,d:any)=>http.put(`/products/offers/${id}`,d),deleteOffer:(id:number)=>http.delete(`/products/offers/${id}`),productPolicies:()=>http.get('/products/policies'),createProductPolicy:(d:any)=>http.post('/products/policies',d),updateProductPolicy:(id:number,d:any)=>http.put(`/products/policies/${id}`,d),deleteProductPolicy:(id:number)=>http.delete(`/products/policies/${id}`)
}
