-- P5-A补充：允许订单选定套餐后先生成待激活返现计划。
ALTER TABLE customer_cashback_plan
    MODIFY COLUMN activated_at DATETIME NULL COMMENT '实际激活时间，待激活计划为空',
    MODIFY COLUMN status VARCHAR(24) NOT NULL DEFAULT 'PENDING_ACTIVATION' COMMENT 'PENDING_ACTIVATION、ACTIVE、COMPLETED、CANCELLED';
