<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{api}from'../api/admin';
const rows=ref<any[]>([]),visible=ref(false),passwordVisible=ref(false),editing=ref<any>();const form=reactive<any>({username:'',displayName:'',phone:'',email:'',password:''});const password=ref('');
async function load(){try{rows.value=await api.users() as any[]}catch(e:any){ElMessage.error(e.message)}}
function open(row?:any){editing.value=row||null;Object.assign(form,row?{username:row.username,displayName:row.displayName,phone:row.phone,email:row.email,password:''}:{username:'',displayName:'',phone:'',email:'',password:''});visible.value=true}
async function save(){try{if(editing.value)await api.updateUser(editing.value.id,form);else await api.createUser(form);ElMessage.success('管理员已保存');visible.value=false;load()}catch(e:any){ElMessage.error(e.message)}}
async function reset(row:any){password.value='';editing.value=row;passwordVisible.value=true}
async function savePassword(){try{await api.changeUserPassword(editing.value.id,password.value);ElMessage.success('密码已重置');passwordVisible.value=false}catch(e:any){ElMessage.error(e.message)}}
async function toggle(row:any){const status=row.status==='ENABLED'?'DISABLED':'ENABLED';try{await ElMessageBox.confirm(`确认${status==='ENABLED'?'启用':'停用'}管理员“${row.username}”？`,'确认操作',{type:'warning'});await api.changeUserStatus(row.id,status);ElMessage.success('状态已更新');load()}catch(e:any){if(e!=='cancel')ElMessage.error(e.message)}}onMounted(load);
</script>
<template><div class="page"><div class="page-heading"><div><h1>管理员</h1><p>管理员账户和联系方式均保存于数据库；密码仅保存 BCrypt 哈希。</p></div><el-button type="primary" @click="open()">新增管理员</el-button></div><div class="table-card"><el-table :data="rows"><el-table-column prop="username" label="登录账号" min-width="130"/><el-table-column prop="displayName" label="姓名" min-width="120"/><el-table-column prop="phone" label="手机号" min-width="130"/><el-table-column prop="email" label="邮箱" min-width="180"/><el-table-column prop="roleCode" label="角色" width="110"/><el-table-column prop="status" label="状态" width="110"><template #default="s"><el-tag :type="s.row.status==='ENABLED'?'success':'info'">{{s.row.status==='ENABLED'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="lastLoginAt" label="最近登录" min-width="170"/><el-table-column label="操作" width="230" fixed="right"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link type="primary" @click="reset(s.row)">重置密码</el-button><el-button link :type="s.row.status==='ENABLED'?'danger':'success'" @click="toggle(s.row)">{{s.row.status==='ENABLED'?'停用':'启用'}}</el-button></template></el-table-column></el-table></div><el-dialog v-model="visible" :title="editing?'编辑管理员':'新增管理员'" width="520"><el-form label-width="90"><el-form-item label="登录账号" required><el-input v-model="form.username" :disabled="!!editing"/></el-form-item><el-form-item label="姓名" required><el-input v-model="form.displayName"/></el-form-item><el-form-item label="手机号"><el-input v-model="form.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item v-if="!editing" label="初始密码" required><el-input v-model="form.password" type="password" show-password/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog><el-dialog v-model="passwordVisible" title="重置管理员密码" width="420"><el-input v-model="password" type="password" show-password placeholder="请输入新密码"/><template #footer><el-button @click="passwordVisible=false">取消</el-button><el-button type="primary" @click="savePassword">确认重置</el-button></template></el-dialog></div></template>
