package com.cmhk.business.module.admin.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.cmhk.business.common.cache.CacheClient;
import com.cmhk.business.module.admin.entity.*;
import com.cmhk.business.module.admin.mapper.*;
import com.cmhk.business.module.mobile.entity.MobilePlanOrder;
import com.cmhk.business.module.mobile.service.OrderStatusHistoryService;
import com.cmhk.business.module.mobile.service.OrderStatusMappingService;
import com.cmhk.business.module.mobile.mapper.MobilePlanOrderMapper;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.math.BigDecimal;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.util.*;

@Service
public class ReconciliationService {
    private final ReconciliationImportMapper importMapper; private final ReconciliationRowMapper rowMapper; private final MobilePlanOrderMapper orderMapper; private final IccidInventoryMapper iccidMapper; private final TabularFileReader fileReader; private final ObjectMapper objectMapper; private final OperationLogService logService; private final CacheClient cacheClient; private final OrderStatusMappingService statusMappingService; private final OrderStatusHistoryService historyService;
    public ReconciliationService(ReconciliationImportMapper importMapper,ReconciliationRowMapper rowMapper,MobilePlanOrderMapper orderMapper,IccidInventoryMapper iccidMapper,TabularFileReader fileReader,ObjectMapper objectMapper,OperationLogService logService,CacheClient cacheClient,OrderStatusMappingService statusMappingService,OrderStatusHistoryService historyService){this.importMapper=importMapper;this.rowMapper=rowMapper;this.orderMapper=orderMapper;this.iccidMapper=iccidMapper;this.fileReader=fileReader;this.objectMapper=objectMapper;this.logService=logService;this.cacheClient=cacheClient;this.statusMappingService=statusMappingService;this.historyService=historyService;}

    @Transactional public Map<String,Object> preview(MultipartFile file,String operator){String hash=sha256(file);long duplicated=importMapper.selectCount(new LambdaQueryWrapper<ReconciliationImport>().eq(ReconciliationImport::getFileHash,hash).ne(ReconciliationImport::getStatus,"CANCELLED"));if(duplicated>0)throw new IllegalArgumentException("该文件已经导入，不能重复上传");List<Map<String,String>> source=fileReader.read(file);if(source.isEmpty())throw new IllegalArgumentException("文件中没有可导入的数据");
        ReconciliationImport batch=new ReconciliationImport();batch.setFileName(file.getOriginalFilename());batch.setFileHash(hash);batch.setStatus("PREVIEW");batch.setTotalCount(source.size());batch.setSuccessCount(0);batch.setFailedCount(0);batch.setUnmatchedCount(0);batch.setOperatorName(operator);importMapper.insert(batch);
        int matched=0,unmatched=0,ambiguous=0;for(Map<String,String> sourceRow:source){ReconciliationRow row=toRow(batch.getId(),sourceRow);Match match=match(row);row.setMatchedOrderId(match.orderId());row.setMatchMethod(match.method());row.setMatchStatus(match.status());row.setExceptionReason(match.reason());rowMapper.insert(row);if("MATCHED".equals(match.status()))matched++;else if("AMBIGUOUS".equals(match.status()))ambiguous++;else unmatched++;}
        batch.setSuccessCount(matched);batch.setFailedCount(ambiguous);batch.setUnmatchedCount(unmatched);importMapper.updateById(batch);Map<String,Object> summary=new LinkedHashMap<>();summary.put("batch",batch);summary.put("rows",rows(batch.getId()));summary.put("matched",matched);summary.put("unmatched",unmatched);summary.put("ambiguous",ambiguous);logService.record(operator,"RECONCILIATION_PREVIEW","RECONCILIATION_IMPORT",batch.getId(),null,Map.of("total",source.size(),"matched",matched,"unmatched",unmatched,"ambiguous",ambiguous),file.getOriginalFilename());invalidateReconciliationCaches();return summary;}

    @Transactional public ReconciliationImport confirm(Long importId,String operator){ReconciliationImport batch=requiredBatch(importId);if(!"PREVIEW".equals(batch.getStatus()))throw new IllegalArgumentException("只有预览状态的批次可以确认");List<ReconciliationRow> rows=rows(importId);int success=0,failed=0,unmatched=0;for(ReconciliationRow row:rows){if(row.getMatchedOrderId()==null){if("AMBIGUOUS".equals(row.getMatchStatus()))failed++;else unmatched++;continue;}if(!apply(row,operator)){failed++;continue;}row.setMatchStatus("CONFIRMED");row.setResolvedAt(LocalDateTime.now());row.setResolvedBy(operator);rowMapper.updateById(row);success++;}
        batch.setStatus("CONFIRMED");batch.setSuccessCount(success);batch.setFailedCount(failed);batch.setUnmatchedCount(unmatched);batch.setConfirmedAt(LocalDateTime.now());batch.setOperatorName(operator);importMapper.updateById(batch);logService.record(operator,"RECONCILIATION_CONFIRM","RECONCILIATION_IMPORT",importId,null,batch,null);invalidateReconciliationCaches();return batch;}

    @Transactional public ReconciliationRow manualMatch(Long rowId,Long orderId,String operator){ReconciliationRow row=requiredRow(rowId);MobilePlanOrder order=orderMapper.selectById(orderId);if(order==null)throw new IllegalArgumentException("订单不存在");row.setMatchedOrderId(orderId);row.setMatchMethod("MANUAL");row.setMatchStatus("MANUAL_MATCHED");row.setExceptionReason(null);row.setResolvedAt(LocalDateTime.now());row.setResolvedBy(operator);rowMapper.updateById(row);ReconciliationImport batch=requiredBatch(row.getImportId());if("CONFIRMED".equals(batch.getStatus())){if(apply(row,operator)){row.setMatchStatus("CONFIRMED");rowMapper.updateById(row);}}refreshCounts(batch);logService.record(operator,"RECONCILIATION_MANUAL_MATCH","RECONCILIATION_ROW",rowId,null,Map.of("orderId",orderId),null);invalidateReconciliationCaches();return row;}

    public List<ReconciliationImport> batches(){return importMapper.selectList(new LambdaQueryWrapper<ReconciliationImport>().orderByDesc(ReconciliationImport::getId));}
    public Map<String,Object> detail(Long id){return Map.of("batch",requiredBatch(id),"rows",rows(id));}
    public List<ReconciliationRow> exceptions(){return rowMapper.selectList(new LambdaQueryWrapper<ReconciliationRow>().in(ReconciliationRow::getMatchStatus,List.of("UNMATCHED","AMBIGUOUS","STATUS_EXCEPTION")).orderByDesc(ReconciliationRow::getId));}

    private void invalidateReconciliationCaches(){cacheClient.invalidateNamespacesAfterCommit(AdminCacheKeys.DASHBOARD,AdminCacheKeys.ORDERS,AdminCacheKeys.CUSTOMERS);}

    private ReconciliationRow toRow(Long importId,Map<String,String> values){ReconciliationRow row=new ReconciliationRow();row.setImportId(importId);row.setRowNumber(integer(values.get("__rowNumber")));try{row.setRawData(objectMapper.writeValueAsString(values));}catch(Exception e){row.setRawData(values.toString());}row.setUmallOrderNo(first(values,"UMALL订单号","UMALL Order No","订单号","umall_order_no"));row.setIccid(first(values,"ICCID","iccid","SIM卡号"));row.setPhone(first(values,"手机号","联系电话","服务号码","MSISDN","phone"));row.setPlanName(first(values,"套餐","套餐名称","Plan"));row.setUmallStatus(first(values,"UMALL状态","办理状态","订单状态","umall_status"));row.setReviewStatus(first(values,"审核状态","审核结果"));row.setSupplementStatus(first(values,"补件状态","补件原因"));row.setActivationStatus(first(values,"激活状态","上台状态"));row.setContractStatus(first(values,"合约状态"));row.setCommissionAmount(decimal(first(values,"佣金","佣金金额","Commission")));return row;}
    private Match match(ReconciliationRow row){if(notBlank(row.getUmallOrderNo())){List<MobilePlanOrder> orders=orderMapper.selectList(new LambdaQueryWrapper<MobilePlanOrder>().eq(MobilePlanOrder::getUmallOrderNo,row.getUmallOrderNo()));if(orders.size()==1)return new Match(orders.get(0).getId(),"UMALL_ORDER_NO","MATCHED",null);if(orders.size()>1)return new Match(null,"UMALL_ORDER_NO","AMBIGUOUS","UMALL订单号匹配到多条订单");}
        if(notBlank(row.getIccid())){List<IccidInventory> cards=iccidMapper.selectList(new LambdaQueryWrapper<IccidInventory>().eq(IccidInventory::getIccid,row.getIccid()).isNotNull(IccidInventory::getCurrentOrderId));Set<Long> ids=new HashSet<>();cards.forEach(c->ids.add(c.getCurrentOrderId()));if(ids.size()==1)return new Match(ids.iterator().next(),"ICCID","MATCHED",null);if(ids.size()>1)return new Match(null,"ICCID","AMBIGUOUS","ICCID匹配到多条订单");}
        if(notBlank(row.getPhone())){List<MobilePlanOrder> orders=orderMapper.selectList(new LambdaQueryWrapper<MobilePlanOrder>().eq(MobilePlanOrder::getContactPhone,row.getPhone()));if(orders.size()==1)return new Match(orders.get(0).getId(),"PHONE","MATCHED",null);if(orders.size()>1)return new Match(null,"PHONE","AMBIGUOUS","手机号匹配到多条订单");}return new Match(null,null,"UNMATCHED","未按订单号、ICCID或手机号匹配到唯一订单");}
    /** 未知状态只更新对账行为异常，不覆盖订单上的任何状态字段。 */
    private boolean apply(ReconciliationRow row,String operator){MobilePlanOrder order=orderMapper.selectById(row.getMatchedOrderId());if(order==null)throw new IllegalArgumentException("匹配订单不存在");OrderStatusMappingService.MappingResult mapping=statusMappingService.map(row.getUmallStatus(),row.getReviewStatus(),row.getSupplementStatus(),row.getActivationStatus());if(mapping.unknown()){row.setMatchStatus("STATUS_EXCEPTION");row.setExceptionReason(mapping.reason());row.setResolvedAt(null);row.setResolvedBy(null);rowMapper.updateById(row);return false;}String beforeJoincom=order.getStatus();String beforeReview=order.getReviewStatus();String beforeSupplement=order.getSupplementStatus();String beforeActivation=order.getActivationStatus();String beforeContract=order.getContractStatus();String beforeUmall=order.getUmallStatus();if(notBlank(row.getUmallOrderNo()))order.setUmallOrderNo(row.getUmallOrderNo());if(notBlank(row.getPhone()))order.setServiceNumber(row.getPhone());if(notBlank(row.getUmallStatus()))order.setUmallStatus(row.getUmallStatus());if(notBlank(row.getReviewStatus()))order.setReviewStatus(row.getReviewStatus());if(notBlank(row.getSupplementStatus()))order.setSupplementStatus(row.getSupplementStatus());if(notBlank(row.getActivationStatus()))order.setActivationStatus(row.getActivationStatus());if(notBlank(row.getContractStatus()))order.setContractStatus(row.getContractStatus());if(mapping.standardStatus()!=null){order.setStatus(mapping.standardStatus());order.setStatusUpdatedAt(LocalDateTime.now());}order.setReconciliationStatus("已对账");orderMapper.updateById(order);historyService.record(order.getId(),"JOINCOM",beforeJoincom,order.getStatus(),"RECONCILIATION",null,operator,"CMHK文件确认");historyService.record(order.getId(),"UMALL",beforeUmall,order.getUmallStatus(),"RECONCILIATION",null,operator,null);historyService.record(order.getId(),"UMALL_REVIEW",beforeReview,order.getReviewStatus(),"RECONCILIATION",null,operator,null);historyService.record(order.getId(),"UMALL_SUPPLEMENT",beforeSupplement,order.getSupplementStatus(),"RECONCILIATION",null,operator,null);historyService.record(order.getId(),"ACTIVATION",beforeActivation,order.getActivationStatus(),"RECONCILIATION",null,operator,null);historyService.record(order.getId(),"CONTRACT",beforeContract,order.getContractStatus(),"RECONCILIATION",null,operator,null);return true;}
    private void refreshCounts(ReconciliationImport batch){List<ReconciliationRow> rows=rows(batch.getId());batch.setSuccessCount((int)rows.stream().filter(r->"CONFIRMED".equals(r.getMatchStatus())||"MANUAL_MATCHED".equals(r.getMatchStatus())||"MATCHED".equals(r.getMatchStatus())).count());batch.setFailedCount((int)rows.stream().filter(r->"AMBIGUOUS".equals(r.getMatchStatus())||"STATUS_EXCEPTION".equals(r.getMatchStatus())).count());batch.setUnmatchedCount((int)rows.stream().filter(r->"UNMATCHED".equals(r.getMatchStatus())).count());importMapper.updateById(batch);}
    private ReconciliationImport requiredBatch(Long id){ReconciliationImport v=importMapper.selectById(id);if(v==null)throw new IllegalArgumentException("导入批次不存在");return v;}private ReconciliationRow requiredRow(Long id){ReconciliationRow v=rowMapper.selectById(id);if(v==null)throw new IllegalArgumentException("对账明细不存在");return v;}private List<ReconciliationRow> rows(Long id){return rowMapper.selectList(new LambdaQueryWrapper<ReconciliationRow>().eq(ReconciliationRow::getImportId,id).orderByAsc(ReconciliationRow::getRowNumber));}
    private String sha256(MultipartFile file){try{MessageDigest md=MessageDigest.getInstance("SHA-256");return HexFormat.of().formatHex(md.digest(file.getBytes()));}catch(Exception e){throw new IllegalArgumentException("无法计算文件摘要");}}private String first(Map<String,String> m,String...keys){for(String k:keys)if(notBlank(m.get(k)))return m.get(k).trim();return null;}private boolean notBlank(String v){return v!=null&&!v.isBlank();}private boolean contains(String v,String q){return v!=null&&v.contains(q);}private Integer integer(String v){try{return Integer.valueOf(v);}catch(Exception e){return null;}}private BigDecimal decimal(String v){try{return notBlank(v)?new BigDecimal(v.replace("HK$","").replace(",","").trim()):null;}catch(Exception e){return null;}}
    private record Match(Long orderId,String method,String status,String reason){}
}
