import {createRouter,createWebHashHistory} from 'vue-router'
import {session} from '../api/http'
import AdminLayout from '../layout/AdminLayout.vue'
const routes=[{path:'/login',component:()=>import('../views/LoginView.vue'),meta:{public:true,title:'管理员登录'}},{path:'/',component:AdminLayout,children:[
 {path:'',component:()=>import('../views/DashboardView.vue'),meta:{title:'首页'}},{path:'iccids',redirect:'/resources/iccids'},{path:'resources/iccids',component:()=>import('../views/IccidView.vue'),meta:{title:'ICCID 卡池'}},{path:'resources/virtual-iccid-replacement',component:()=>import('../views/VirtualIccidReplacementView.vue'),meta:{title:'虚拟 ICCID 替换'}},{path:'resources/referral-numbers',component:()=>import('../views/ReferralNumbersView.vue'),meta:{title:'推荐号码接龙'}},{path:'customers',component:()=>import('../views/CustomersView.vue'),meta:{title:'客户管理'}},{path:'customers/:id',component:()=>import('../views/CustomerDetailView.vue'),meta:{title:'客户详情'}},{path:'orders',component:()=>import('../views/OrdersView.vue'),meta:{title:'订单管理'}},{path:'products',component:()=>import('../views/ProductsView.vue'),meta:{title:'产品管理'}},
 {path:'reconciliation/import',component:()=>import('../views/ReconciliationImportView.vue'),meta:{title:'甲方文件导入'}},{path:'reconciliation/records',component:()=>import('../views/ReconciliationRecordsView.vue'),meta:{title:'对账记录'}},{path:'reconciliation/exceptions',component:()=>import('../views/ReconciliationExceptionsView.vue'),meta:{title:'异常匹配'}},
 {path:'secondary/channels',component:()=>import('../views/SecondaryChannelsView.vue'),meta:{title:'渠道档案'}},{path:'secondary/rules',component:()=>import('../views/SecondaryRulesView.vue'),meta:{title:'结算规则'}},{path:'secondary/orders',component:()=>import('../views/SecondaryOrdersView.vue'),meta:{title:'渠道订单'}},{path:'secondary/settlements',component:()=>import('../views/SettlementRecordsView.vue'),meta:{title:'结算记录'}},{path:'users',component:()=>import('../views/AdminUsersView.vue'),meta:{title:'管理员',adminOnly:true}},{path:'logs',component:()=>import('../views/LogsView.vue'),meta:{title:'操作日志'}}]}]
const router=createRouter({history:createWebHashHistory(),routes})
router.beforeEach(to=>{document.title=`${String(to.meta.title||'管理后台')} · JOINCOM`;const current=session();if(!to.meta.public&&!current)return'/login';if(to.path==='/login'&&current)return'/';if(to.meta.adminOnly&&current?.role!=='ADMIN')return'/customers';if(current?.scopeType==='CHANNEL'&&!['/customers','/orders','/secondary/orders','/secondary/settlements','/secondary/channels'].some(path=>to.path.startsWith(path)))return'/customers';return true})
export default router
